# Generated by Django 6.0.1 on 2026-02-23 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'A avaliação não pode inferior a 0 estrelas.'), django.core.validators.MaxValueValidator(5, 'A avaliação não pode ser superior a 5 estrelas.')]),
        ),
    ]
